web:
  host: '0.0.0.0'
  port: 8000
planner:
  duration: 30
connectors:
  matrix:
    mxid: '@planner_bot:matrix.org'
    password: 'PlannerPass@43'
    rooms:
      'main': '#first_room:matrix.org'
    homeserver: 'https://matrix.org'
    nick: 'Your Friend'
    device_id: 'OPSDroid'
    device_name: 'opsdroid'
    enable_encryption: True
    welcome-message: False
welcome-message: false

skills:
  greetings:
    path: skills/greetings.py
  help:
#  - name: help
    path: skills/help.py
  main:
#  - name: main
    path: skills/main.py
  accept_invite:
    path: skills/accept_invite.py
  welcome-skill:
    path: skills/welcome_skill.py

#databases:
#  mongo:
#    type: mongodb
#    database: nlp_bot
#    host: localhost
#    port: 27017