planner:
  duration: 30
connectors:
  matrix:
    mxid: '@planner_bot:matrix.org'
    password: 'PlannerPass@43'
    rooms:
      'main': '#first_room:matrix.org'
    homeserver: 'https://matrix.org'
    nick: 'Your Friend'
    device_id: 'OPSDroid'
    enable_encryption: True
  welcome-message: True

skills:
#  welcome:
#    enabled: true
#    message: 'به دستیار مدیریت رویدادها و وقایع خوش آمدید.'
  greetings:
    path: opsdroid_skills/greetings/greetings.py
  help:
    path: opsdroid_skills/help/help.py
  main:
    path: opsdroid_skills/main/bot.py
  accept_invite:
    path: opsdroid_skills/accept_invite/accept_invite.py