planner:
  duration: 30
connectors:
  matrix:
    mxid: '@planner_bot:matrix.org'
    password: 'PlannerPass@43'
    rooms:
      'main': '#first_room:matrix.org'
    homeserver: 'https://matrix.org'
    nick: 'Your Friend'
    device_id: 'OPSDroid'
    enable_encryption: True

skills:
  greetings:
    path: skills/greetings.py
  help:
  - name: help
    path: skills.help
  main:
  - name: main
    path: skills.main
  accept_invite:
    path: skills/accept_invite.py

debug: true

databases:
  mongo:
    type: mongodb
    database: nlp_bot
    host: localhost
    port: 27017
